app/routes.php
<?php

/**
 * This file is part of Bootstrap CMS by Graham Campbell.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 */

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// send users to the home page
Route::get('/', array('as' => 'base', function () {
    Session::flash('', ''); // work around laravel bug if there is no session yet
    Session::reflash();
    return Redirect::to(Config::get('graham-campbell/core::home', 'pages/home'));
}));

// send users to the posts page
if (Config::get('cms.blogging')) {
    Route::get('blog', array('as' => 'blog', function () {
        Session::flash('', ''); // work around laravel bug if there is no session yet
        Session::reflash();
        return Redirect::route('blog.posts.index');
    }));
}

// page routes
Route::resource('pages', 'GrahamCampbell\BootstrapCMS\Controllers\PageController');

// blog routes
if (Config::get('cms.blogging')) {
    Route::resource('blog/posts', 'GrahamCampbell\BootstrapCMS\Controllers\PostController');
    Route::resource('blog/posts.comments', 'GrahamCampbell\BootstrapCMS\Controllers\CommentController');
}

// event routes
if (Config::get('cms.events')) {
    Route::resource('events', 'GrahamCampbell\BootstrapCMS\Controllers\EventController');
}

// caching routes
Route::get('caching', array(
    'as' => 'caching.index',
    'uses' => 'GrahamCampbell\BootstrapCMS\Controllers\CachingController@getIndex'
));

app/assets.php
<?php

/**
 * This file is part of Bootstrap CMS by Graham Campbell.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 */

/*
|--------------------------------------------------------------------------
| Application Assets
|--------------------------------------------------------------------------
|
| Here is where you can register all of the assets for an application.
| This leverages the power of lightgear/asset.
|
*/

$styles = array();
if (Config::get('theme.name') == 'default') {
    $styles[] = 'css/bootstrap.min.css';
} elseif (Config::get('theme.name') == 'legacy') {
    $styles[] = 'css/bootstrap.min.css';
    $styles[] = 'css/bootstrap-theme.min.css';
} else {
    $styles[] = 'css/bootstrap.'.Config::get('theme.name').'.min.css';
}
$styles[] = 'css/cms-main.css';
if (Config::get('laravel-debugbar::config.enabled')) {
    $styles[] = 'maximebf\debugbar\src\DebugBar\Resources\vendor\highlightjs\styles\github.css';
}

Asset::registerStyles($styles, '', 'main');

$scripts = array(
    'js/cms-timeago.js',
    'js/cms-restfulizer.js',
    'js/cms-carousel.js',
    'js/cms-alerts.js'
);
if (Config::get('laravel-debugbar::config.enabled')) {
    $scripts[] = 'maximebf\debugbar\src\DebugBar\Resources\vendor\highlightjs\highlight.pack.js';
}

Asset::registerScripts($scripts, '', 'main');

Asset::registerStyles(array(
    'css/bootstrap-switch.css',
    'css/bootstrap-markdown.min.css'
), '', 'form');

Asset::registerScripts(array(
    'js/bootstrap-switch.js',
    'js/bootstrap-markdown.js'
), '', 'form');

Asset::registerStyles(array(
    'css/bootstrap-datetimepicker.min.css'
), '', 'picker');

Asset::registerScripts(array(
    'js/bootstrap-datetimepicker.min.js',
    'js/cms-picker.js'
), '', 'picker');

Asset::registerScripts(array(
    'js/cms-comment-core.js',
    'js/cms-comment-edit.js',
    'js/cms-comment-delete.js',
    'js/cms-comment-create.js',
    'js/cms-comment-fetch.js',
    'js/cms-comment-main.js'
), '', 'comment');

app/filters.php
<?php

/**
 * This file is part of Bootstrap CMS by Graham Campbell.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 */

use Illuminate\Session\TokenMismatchException;
use Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException;

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function ($request) {
    Event::fire('page.load', array(array('Path' => $request->path(), 'Headers' => $request->header())));
});

App::after(function ($request, $response) {
    //
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function () {
    if (Session::token() != Input::get('_token')) {
        throw new TokenMismatchException();
    }
});

/*
|--------------------------------------------------------------------------
| Throttling Filters
|--------------------------------------------------------------------------
|
| This is where we check the user is not spamming our system by limiting
| certain types of actions with a throttler.
|
*/

Route::filter('throttle.comment', function ($route, $request) {
    // check if we've reached the rate limit, but don't hit the throttle yet
    // we can hit the throttle later on in the if validation passes
    if (!Throttle::check($request, 10, 1)) {
        throw new TooManyRequestsHttpException(60, 'Rate limit exceed.');
    }
});

app/listeners.php
<?php

/**
 * This file is part of Bootstrap CMS by Graham Campbell.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 */

/*
|--------------------------------------------------------------------------
| Application Event Listeners
|--------------------------------------------------------------------------
|
| Here is where you can register all of the listeners for an application.
|
*/

if (Config::get('graham-campbell/core::commands')) {
    $subscriber = App::make('GrahamCampbell\BootstrapCMS\Subscribers\CommandSubscriber');
    Event::subscribe($subscriber);
}

$subscriber = App::make('GrahamCampbell\BootstrapCMS\Subscribers\CoreSubscriber');
Event::subscribe($subscriber);

$subscriber = App::make('GrahamCampbell\BootstrapCMS\Subscribers\NavigationSubscriber');
Event::subscribe($subscriber);

$observer = App::make('GrahamCampbell\BootstrapCMS\Observers\PageObserver');
PageProvider::observe($observer);

app/views/events/delete.blade.php
<div id="delete_event" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Are you sure?</h4>
            </div>
            <div class="modal-body">
                <p>You are about to delete this event! This process cannot be undone.</p>
                <p>Are you sure you wish to continue?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-success" href="{{ URL::route('events.destroy', array('events' => $event->id)) }}" data-token="{{ Session::getToken() }}" data-method="DELETE">Yes</a>
                <button class="btn btn-danger" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

app/views/events/deletes.blade.php
@foreach ($events as $event)
    <div id="delete_event_{{ $event->id }}" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <p>You are about to delete this event! This process cannot be undone.</p>
                    <p>Are you sure you wish to continue?</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-success" href="{{ URL::route('events.destroy', array('events' => $event->id)) }}" data-token="{{ Session::getToken() }}" data-method="DELETE">Yes</a>
                    <button class="btn btn-danger" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
@endforeach

app/views/events/edit.blade.php
@extends(Config::get('views.default', 'layouts.default'))

@section('title')
Edit {{{ $event->title }}}
@stop

@section('top')
<div class="page-header">
<h1>Edit {{{ $event->title }}}</h1>
</div>
@stop

@section('content')
<div class="row">
    <div class="col-xs-6">
        <p class="lead">
            Please edit the event:
        </p>
    </div>
    <div class="col-xs-6">
        <div class="pull-right">
            <a class="btn btn-success" href="{{ URL::route('events.show', array('events' => $event->id)) }}"><i class="fa fa-file-text"></i> Show Event</a> <a class="btn btn-danger" href="#delete_event" data-toggle="modal" data-target="#delete_event"><i class="fa fa-times"></i> Delete Event</a>
        </div>
        </div>
</div>
<hr>
<div class="well">
    <?php
    $form = array('url' => URL::route('events.update', array('events' => $event->id)),
        'method'   => 'PATCH',
        'button'   => 'Save Event',
        'defaults' => array(
            'title'    => $event->title,
            'date'     => $event->date->format('d/m/Y H:i'),
            'location' => $event->location,
            'body'     => $event->body,
    ));
    ?>
    @include('events.form')
</div>
@stop

@section('bottom')
@auth('edit')
@include('events.delete')
@endauth
@stop

@section('css')
{{ Asset::styles('form') }}
{{ Asset::styles('picker') }}
@stop

@section('js')
{{ Asset::scripts('form') }}
{{ HTML::script('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.6.0/moment.min.js') }}
{{ Asset::scripts('picker') }}
@stop

app/views/events/index.blade.php
@extends(Config::get('views.default', 'layouts.default'))

@section('title')
Events
@stop

@section('top')
<div class="page-header">
<h1>Events</h1>
</div>
@stop

@section('content')
<div class="row">
    <div class="col-xs-8">
        <p class="lead">
            @if (count($events) == 0)
                There are currently no events.
            @else
                Here you may find our events:
            @endif
        </p>
    </div>
    @auth('edit')
        <div class="col-xs-4">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ URL::route('events.create') }}"><i class="fa fa-calendar"></i> New Event</a>
            </div>
        </div>
    @endauth
</div>
@foreach($events as $event)
    <h2>{{ $event->title }}</h2>
    <p>
        <strong>{{ $event->date->format('l jS F Y H:i') }}</strong>
    </p>
    <p>
        <a class="btn btn-success" href="{{ URL::route('events.show', array('events' => $event->id)) }}"><i class="fa fa-file-text"></i> Show Event</a>
        @auth('edit')
             <a class="btn btn-info" href="{{ URL::route('events.edit', array('events' => $event->id)) }}"><i class="fa fa-pencil-square-o"></i> Edit Event</a> <a class="btn btn-danger" href="#delete_event_{{ $event->id }}" data-toggle="modal" data-target="#delete_event_{{ $event->id }}"><i class="fa fa-times"></i> Delete Event</a>
        @endauth
    </p>
    <br>
@endforeach
{{ $links }}
@stop

@section('bottom')
@auth('edit')
    @include('events.deletes')
@endauth
@stop

app/views/events/show.blade.php
@extends(Config::get('views.default', 'layouts.default'))

@section('title')
{{{ $event->title }}}
@stop

@section('top')
<div class="page-header">
<h1>{{{ $event->title }}}</h1>
</div>
@stop

@section('content')
@auth('edit')
    <div class="well clearfix">
        <div class="hidden-xs">
            <div class="col-xs-6">
                <p>
                    <strong>Event Owner:</strong> {{ $event->owner }}
                </p>
                <a class="btn btn-info" href="{{ URL::route('events.edit', array('events' => $event->id)) }}"><i class="fa fa-pencil-square-o"></i> Edit Event</a> <a class="btn btn-danger" href="#delete_event" data-toggle="modal" data-target="#delete_event"><i class="fa fa-times"></i> Delete Event</a>
            </div>
            <div class="col-xs-6">
                <div class="pull-right">
                    <p>
                        <em>Event Created: {{ HTML::ago($event->created_at) }}</em>
                    </p>
                    <p>
                        <em>Last Updated: {{ HTML::ago($event->updated_at) }}</em>
                    </p>
                </div>
            </div>
        </div>
        <div class="visible-xs">
            <div class="col-xs-12">
                <p>
                    <strong>Event Owner:</strong> {{ $event->owner }}
                </p>
                <p>
                    <strong>Event Created:</strong> {{ HTML::ago($event->created_at) }}
                </p>
                <p>
                    <strong>Last Updated:</strong> {{ HTML::ago($event->updated_at) }}
                </p>
                <a class="btn btn-info" href="{{ URL::route('events.edit', array('events' => $event->id)) }}"><i class="fa fa-pencil-square-o"></i> Edit Event</a> <a class="btn btn-danger" href="#delete_event" data-toggle="modal" data-target="#delete_event"><i class="fa fa-times"></i> Delete Event</a>
            </div>
        </div>
    </div>
    <hr>
@endauth
<div class="well clearfix">
    <div class="hidden-xs">
        <div class="col-xs-6">
            <p class="lead">Date: {{ $event->date->format('l jS F Y H:i') }}</p>
        </div>
        <div class="col-xs-6">
            <div class="pull-right">
                <p class="lead">Location: {{ $event->location }}</p>
            </div>
        </div>
    </div>
    <div class="visible-xs">
        <div class="col-xs-12">
            <p class="lead">Date: {{ $event->date->format('l jS F Y H:i') }}</p>
            <p class="lead">Location: {{ $event->location }}</p>
        </div>
    </div>
    <div class="col-xs-12">
        <hr>
        {{ str_replace('<p>', '<p class="lead">', Markdown::render($event->body)) }}
    </div>
</div>
@stop

@section('bottom')
@auth('edit')
@include('events.delete')
@endauth
@stop

@section('css')
@auth('mod')
{{ Asset::styles('form') }}
@endauth
@stop

@section('js')
@auth('mod')
{{ Asset::scripts('form') }}
@endauth
@stop

app/views/layouts/email.blade.php
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
</head>
<body>
<h2>{{{ $subject }}}</h2>
@section('content')
@show
<br>
<p>
Thank you, <br>
The Support Team
</p>
</body>
</html>

app/views/pages/delete.blade.php
<div id="delete_page" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Are you sure?</h4>
            </div>
            <div class="modal-body">
                <p>You are about to delete this page! This process cannot be undone.</p>
                <p>Are you sure you wish to continue?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-success" href="{{ URL::route('pages.destroy', array('pages' => $page->slug)) }}" data-token="{{ Session::getToken() }}" data-method="DELETE">Yes</a>
                <button class="btn btn-danger" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

app/views/pages/edit.blade.php
@extends(Config::get('views.default', 'layouts.default'))

@section('title')
Edit {{{ $page->title }}}
@stop

@section('top')
<div class="page-header">
<h1>Edit {{{ $page->title }}}</h1>
</div>
@stop

@section('content')
<div class="row">
    <div class="col-xs-6">
        <p class="lead">
            Please edit the page:
        </p>
    </div>
    <div class="col-xs-6">
        <div class="pull-right">
            <a class="btn btn-success" href="{{ URL::route('pages.show', array('pages' => $page->slug)) }}"><i class="fa fa-file-text"></i> Show Page</a> <a class="btn btn-danger" href="#delete_page" data-toggle="modal" data-target="#delete_page"><i class="fa fa-times"></i> Delete Page</a>
        </div>
    </div>
</div>
<hr>
<div class="well">
    <?php
    $form = array('url' => URL::route('pages.update', array('pages' => $page->slug)),
        'method' => 'PATCH',
        'button' => 'Save Page',
        'defaults' => array(
            'title' => $page->title,
            'nav_title' => $page->nav_title,
            'slug' => $page->slug,
            'icon' => $page->icon,
            'body' => $page->body,
            'css' => $page->css,
            'js' => $page->js,
            'show_title' => ($page->show_title == true),
            'show_nav' => ($page->show_nav == true),
    ));
    ?>
    @include('pages.form')
</div>
@stop

@section('bottom')
@auth('edit')
    @include('pages.delete')
@endauth
@stop

@section('css')
{{ Asset::styles('form') }}
@stop

@section('js')
{{ Asset::scripts('form') }}
@stop

app/views/posts/comment.blade.php
<div id="comment_{{ $comment->id }}" class="well clearfix col-xs-12 animated bounceIn{{ rand(0, 1) ? 'Left': 'Right' }}" data-pk="{{ $comment->id }}" data-ver="{{ $comment->version }}">
    @auth('mod')
        <div class="col-md-9 col-sm-8">
            <p><strong>{{ $comment->author }}</strong> - {{ HTML::ago($comment->created_at, 'timeago_comment_'.$comment->id) }}</p>
            <p id="main_comment_{{ $comment->id }}" class="main">{{ nl2br(e($comment->body)) }}</p>
        </div>
        <div class="hidden-xs">
            <div class="col-md-3 col-sm-4">
                <div class="pull-right">
                    <a id="editable_comment_{{ $comment->id }}_1" class="btn btn-info editable" href="#edit_comment" data-pk="{{ $comment->id }}"><i class="fa fa-pencil-square-o"></i> Edit</a> <a id="deletable_comment_{{ $comment->id }}_1" class="btn btn-danger deletable" href="{{ URL::route('blog.posts.comments.destroy', array('posts' => $post_id, 'comments' => $comment->id)) }}"><i class="fa fa-times"></i> Delete</a>
                </div>
            </div>
        </div>
        <div class="visible-xs">
            <div class="col-xs-12">
                <a id="editable_comment_{{ $comment->id }}_2" class="btn btn-info editable" href="#edit_comment" data-pk="{{ $comment->id }}"><i class="fa fa-pencil-square-o"></i> Edit</a> <a id="deletable_comment_{{ $comment->id }}_2" class="btn btn-danger deletable" href="{{ URL::route('blog.posts.comments.destroy', array('posts' => $post_id, 'comments' => $comment->id)) }}"><i class="fa fa-times"></i> Delete</a>
            </div>
        </div>
    @else
        <div class="col-xs-12">
            <p><strong>{{ $comment->author }}</strong> - {{ HTML::ago($comment->created_at, 'timeago_comment_'.$comment->id) }}</p>
            <p id="main_comment_{{ $comment->id }}" class="main">{{ nl2br(e($comment->body)) }}</p>
        </div>
    @endauth
</div>

app/views/posts/index.blade.php
@extends(Config::get('views.default', 'layouts.default'))

@section('title')
Blog
@stop

@section('top')
<div class="page-header">
<h1>Blog</h1>
</div>
@stop

@section('content')
<div class="row">
    <div class="col-xs-8">
        <p class="lead">
            @if (count($posts) == 0)
                There are currently no blog posts.
            @else
                Here you may find our blog posts:
            @endif
        </p>
    </div>
    @auth('blog')
        <div class="col-xs-4">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ URL::route('blog.posts.create') }}"><i class="fa fa-book"></i> New Post</a>
            </div>
        </div>
    @endauth
</div>
@foreach($posts as $post)
    <h2>{{ $post->title }}</h2>
    <p>
        <strong>{{ $post->summary }}</strong>
    </p>
    <p>
        <a class="btn btn-success" href="{{ URL::route('blog.posts.show', array('posts' => $post->id)) }}"><i class="fa fa-file-text"></i> Show Post</a>
        @auth('blog')
             <a class="btn btn-info" href="{{ URL::route('blog.posts.edit', array('posts' => $post->id)) }}"><i class="fa fa-pencil-square-o"></i> Edit Post</a> <a class="btn btn-danger" href="#delete_post_{{ $post->id }}" data-toggle="modal" data-target="#delete_post_{{ $post->id }}"><i class="fa fa-times"></i> Delete Post</a>
        @endauth
    </p>
    <br>
@endforeach
{{ $links }}
@stop

@section('bottom')
@auth('blog')
    @include('posts.deletes')
@endauth
@stop

app/views/posts/show.blade.php
@extends(Config::get('views.default', 'layouts.default'))

@section('title')
{{{ $post->title }}}
@stop

@section('top')
<div class="page-header">
<h1>{{{ $post->title }}}</h1>
</div>
@stop

@section('content')
@auth('blog')
    <div class="well clearfix">
        <div class="hidden-xs">
            <div class="col-xs-6">
                <p>
                    <strong>Post Owner:</strong> {{ $post->owner }}
                </p>
                <a class="btn btn-info" href="{{ URL::route('blog.posts.edit', array('posts' => $post->id)) }}"><i class="fa fa-pencil-square-o"></i> Edit Post</a> <a class="btn btn-danger" href="#delete_post" data-toggle="modal" data-target="#delete_post"><i class="fa fa-times"></i> Delete Post</a>
            </div>
            <div class="col-xs-6">
                <div class="pull-right">
                    <p>
                        <em>Post Created: {{ HTML::ago($post->created_at) }}</em>
                    </p>
                    <p>
                        <em>Last Updated: {{ HTML::ago($post->updated_at) }}</em>
                    </p>
                </div>
            </div>
        </div>
        <div class="visible-xs">
            <div class="col-xs-12">
                <p>
                    <strong>Post Owner:</strong> {{ $post->owner }}
                </p>
                <p>
                    <strong>Post Created:</strong> {{ HTML::ago($post->created_at) }}
                </p>
                <p>
                    <strong>Last Updated:</strong> {{ HTML::ago($post->updated_at) }}
                </p>
                <a class="btn btn-info" href="{{ URL::route('blog.posts.edit', array('posts' => $post->id)) }}"><i class="fa fa-pencil-square-o"></i> Edit Post</a> <a class="btn btn-danger" href="#delete_post" data-toggle="modal" data-target="#delete_post"><i class="fa fa-times"></i> Delete Post</a>
            </div>
        </div>
    </div>
    <hr>
@endauth

<div class="row">
    <div class="hidden-xs">
        <div class="col-md-8 col-xs-6">
            <p class="lead">{{ $post->summary }}</p>
        </div>
        <div class="col-md-4 col-xs-6">
            <div class="pull-right">
                <p>Author: {{ $post->author }}</p>
            </div>
        </div>
    </div>
    <div class="visible-xs">
        <div class="col-xs-12">
            <p class="lead">{{ $post->summary }}</p>
            <p>Author: {{ $post->author }}</p>
        </div>
    </div>
</div>
<br>

{{ Markdown::render($post->body) }}
<br><hr>

<h3>Comments</h3>
@auth('user')
    <br>
    <div class="well well-sm clearfix">
        {{ Form::open(array('id' => 'commentform', 'url' => URL::route('blog.posts.comments.store', array('posts' => $post->id)), 'method' => 'POST', 'class' => 'form-vertical')) }}
            <div class="form-group">
                <div class="col-xs-12">
                    <textarea id="body" name="body" class="form-control comment-box" placeholder="Type a comment..." rows="3"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12 comment-button">
                    <button id="contact-submit" type="submit" class="btn btn-primary"><i class="fa fa-comment"></i> Post Comment</button> <label id="commentstatus"></label>
                </div>
            </div>
        {{ Form::close() }}
    </div>
@else
<p>
    @if (Config::get('graham-campbell/credentials::regallowed'))
        <strong>Please <a href="{{ URL::route('account.login') }}">login</a> or <a href="{{ URL::route('account.register') }}">register</a> to post a comment.</strong>
    @else
        <strong>Please <a href="{{ URL::route('account.login') }}">login</a> to post a comment.</strong>
    @endif
</p>
@endauth
<br>

<?php $post_id = $post->id; ?>
<div id="comments" data-url="{{ URL::route('blog.posts.comments.index', array('posts' => $post_id)) }}">
    @if (count($comments) == 0)
    <p id="nocomments">There are currently no comments.</p>
    @else
        @foreach ($comments as $comment)
            @include('posts.comment')
        @endforeach
    @endif
</div>
@stop

@section('bottom')
@auth('blog')
@include('posts.delete')
@endauth
@auth('mod')
<div id="edit_comment" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Edit Comment</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    {{ Form::open(array('id' => 'edit_commentform', 'method' => 'PATCH', 'class' => 'form-vertical', 'data-pk' => '0')) }}
                        <input id="verion" name="version" value="1" type="hidden">
                        <div class="form-group">
                            <div class="col-xs-12">
                                <textarea id="edit_body" name="edit_body" class="form-control comment-box" placeholder="Type a comment..." rows="3"></textarea>
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
            <div class="modal-footer">
                <button id="edit_comment_cancel" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="edit_comment_ok" type="button" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>
@endauth
@stop

@section('css')]
{{ Asset::styles('form') }}
@stop

@section('js')
{{ Asset::scripts('form') }}
{{ HTML::script('//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.49/jquery.form.min.js') }}
<script>
var cmsCommentInterval = {{ Config::get('cms.commentfetch') }};
var cmsCommentTime = {{ Config::get('cms.commenttrans') }};
</script>
{{ Asset::scripts('comment') }}
@stop